baseurl = "https://seans-archive.vercel.app/"
title = "sean's archive"
author = "Sean"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "sean's archive"
  disableWebFonts = false
